import type { StyleKey } from './types'
import { getContext2d, query } from './utils'

export const tabGenerate = query<HTMLButtonElement>('#tab-generate')
export const tabSolve = query<HTMLButtonElement>('#tab-solve')
export const tabEdit = query<HTMLButtonElement>('#tab-edit')
export const tabPanelGenerate = query<HTMLElement>('#tab-panel-generate')
export const tabPanelSolve = query<HTMLElement>('#tab-panel-solve')
export const tabPanelEdit = query<HTMLElement>('#tab-panel-edit')

export const generationSelect = query<HTMLSelectElement>('#generation-algorithm')
export const solvingSelect = query<HTMLSelectElement>('#solving-algorithm')
export const floodThemeField = query<HTMLElement>('#flood-theme-field')
export const floodThemeSelect = query<HTMLSelectElement>('#flood-theme-select')
export const dimensionGrid = query<HTMLElement>('#dimension-grid')
export const mazeWidthLabel = query<HTMLElement>('#maze-width-label')
export const mazeHeightField = query<HTMLElement>('#maze-height-field')
export const mazeWidthInput = query<HTMLInputElement>('#maze-width')
export const mazeHeightInput = query<HTMLInputElement>('#maze-height')
export const lockGridRatioInput = query<HTMLInputElement>('#lock-grid-ratio')
export const useViewportRatioInput = query<HTMLInputElement>('#use-viewport-ratio')
export const speedRange = query<HTMLInputElement>('#speed-range')
export const speedLabel = query<HTMLElement>('#speed-label')
export const wallRange = query<HTMLInputElement>('#wall-range')
export const wallLabel = query<HTMLElement>('#wall-label')
export const view2dButton = query<HTMLButtonElement>('#view-2d-btn')
export const view3dButton = query<HTMLButtonElement>('#view-3d-btn')
export const wallHeightField = query<HTMLElement>('#wall-height-field')
export const wallHeightRange = query<HTMLInputElement>('#wall-height-range')
export const wallHeightLabel = query<HTMLElement>('#wall-height-label')
export const styleWallInput = query<HTMLInputElement>('#style-wall')
export const styleCellInput = query<HTMLInputElement>('#style-cell')
export const styleUnlinkedCellInput = query<HTMLInputElement>('#style-unlinked-cell')
export const styleSubPathInput = query<HTMLInputElement>('#style-sub-path')
export const styleVisitInput = query<HTMLInputElement>('#style-visit')
export const stylePathInput = query<HTMLInputElement>('#style-path')
export const styleHeadInput = query<HTMLInputElement>('#style-head')
export const styleFrontierInput = query<HTMLInputElement>('#style-frontier')
export const styleStartInput = query<HTMLInputElement>('#style-start')
export const styleEndInput = query<HTMLInputElement>('#style-end')
export const styleGridInput = query<HTMLInputElement>('#style-grid')
export const styleResetButton = query<HTMLButtonElement>('#style-reset-btn')
export const railWorkbenchButton = query<HTMLButtonElement>('#rail-workbench-btn')
export const railThemesButton = query<HTMLButtonElement>('#rail-themes-btn')
export const panelCollapseButton = query<HTMLButtonElement>('#panel-collapse-btn')
export const panelRail = query<HTMLElement>('.panel-rail')
export const workbenchPanel = query<HTMLElement>('#workbench-panel')
export const themesPanel = query<HTMLElement>('#themes-panel')
export const solveStartReadout = query<HTMLElement>('#solve-start-readout')
export const solveEndReadout = query<HTMLElement>('#solve-end-readout')
export const solveEndPoint = query<HTMLElement>('#solve-end-point')
export const solvePointsGrid = query<HTMLElement>('#solve-points-grid')
export const solvePointsInfo = query<HTMLElement>('#solve-points-info')
export const solvePointsLabel = query<HTMLElement>('#solve-points-label')
export const editStartReadout = query<HTMLElement>('#edit-start-readout')
export const editEndReadout = query<HTMLElement>('#edit-end-readout')
export const runButton = query<HTMLButtonElement>('#run-btn')
export const stepButton = query<HTMLButtonElement>('#step-btn')
export const resetButton = query<HTMLButtonElement>('#reset-btn')
export const focusViewButton = query<HTMLButtonElement>('#focus-view-btn')
export const playDockToggleButton = query<HTMLButtonElement>('#play-dock-toggle')
export const controlBar = query<HTMLElement>('.control-bar')
export const topNav = query<HTMLElement>('#top-nav')
export const packageVersion = query<HTMLElement>('#package-version')
export const statusText = query<HTMLElement>('#status-text')
export const visitedText = query<HTMLElement>('#stat-visited')
export const pathText = query<HTMLElement>('#stat-path')
export const toast = query<HTMLElement>('#toast')
export const canvasWrap = query<HTMLElement>('#canvas-wrap')
export const canvas = query<HTMLCanvasElement>('#maze-canvas')
export const shapeStatus = query<HTMLElement>('#shape-status')
export const shapeUploadButton = query<HTMLButtonElement>('#shape-upload-btn')
export const shapeEditButton = query<HTMLButtonElement>('#shape-edit-btn')
export const shapeClearButton = query<HTMLButtonElement>('#shape-clear-btn')
export const shapeFileInput = query<HTMLInputElement>('#shape-file-input')
export const shapeColorsInput = query<HTMLInputElement>('#shape-colors-visible')
export const shapeColorsToggle = query<HTMLElement>('.shape-colors-toggle')
export const editToolEdgeButton = query<HTMLButtonElement>('#edit-tool-edge')
export const editToolStartButton = query<HTMLButtonElement>('#edit-tool-start')
export const editToolEndButton = query<HTMLButtonElement>('#edit-tool-end')
export const editToolPanButton = query<HTMLButtonElement>('#edit-tool-pan')
export const editOpenAllButton = query<HTMLButtonElement>('#edit-open-all-btn')
export const editCloseAllButton = query<HTMLButtonElement>('#edit-close-all-btn')
export const editClearSolveButton = query<HTMLButtonElement>('#edit-clear-solve-btn')
export const saveMazeButton = query<HTMLButtonElement>('#save-maze-btn')
export const loadMazeButton = query<HTMLButtonElement>('#load-maze-btn')
export const loadMazeFileInput = query<HTMLInputElement>('#load-maze-input')
export const exportSvgButton = query<HTMLButtonElement>('#export-svg-btn')
export const ctx = getContext2d(canvas)

export const styleChipByKey: Record<StyleKey, HTMLElement> = {
  cell: query<HTMLElement>('[data-style-key="cell"]'),
  end: query<HTMLElement>('[data-style-key="end"]'),
  frontier: query<HTMLElement>('[data-style-key="frontier"]'),
  grid: query<HTMLElement>('[data-style-key="grid"]'),
  head: query<HTMLElement>('[data-style-key="head"]'),
  path: query<HTMLElement>('[data-style-key="path"]'),
  start: query<HTMLElement>('[data-style-key="start"]'),
  subPath: query<HTMLElement>('[data-style-key="subPath"]'),
  unlinkedCell: query<HTMLElement>('[data-style-key="unlinkedCell"]'),
  visit: query<HTMLElement>('[data-style-key="visit"]'),
  wall: query<HTMLElement>('[data-style-key="wall"]'),
}

export const styleHexByKey: Record<StyleKey, HTMLElement> = {
  cell: query<HTMLElement>('[data-style-hex="cell"]'),
  end: query<HTMLElement>('[data-style-hex="end"]'),
  frontier: query<HTMLElement>('[data-style-hex="frontier"]'),
  grid: query<HTMLElement>('[data-style-hex="grid"]'),
  head: query<HTMLElement>('[data-style-hex="head"]'),
  path: query<HTMLElement>('[data-style-hex="path"]'),
  start: query<HTMLElement>('[data-style-hex="start"]'),
  subPath: query<HTMLElement>('[data-style-hex="subPath"]'),
  unlinkedCell: query<HTMLElement>('[data-style-hex="unlinkedCell"]'),
  visit: query<HTMLElement>('[data-style-hex="visit"]'),
  wall: query<HTMLElement>('[data-style-hex="wall"]'),
}

export const visibilityButtonByKey: Record<StyleKey, HTMLButtonElement> = {
  cell: query<HTMLButtonElement>('[data-style-visible="cell"]'),
  end: query<HTMLButtonElement>('[data-style-visible="end"]'),
  frontier: query<HTMLButtonElement>('[data-style-visible="frontier"]'),
  grid: query<HTMLButtonElement>('[data-style-visible="grid"]'),
  head: query<HTMLButtonElement>('[data-style-visible="head"]'),
  path: query<HTMLButtonElement>('[data-style-visible="path"]'),
  start: query<HTMLButtonElement>('[data-style-visible="start"]'),
  subPath: query<HTMLButtonElement>('[data-style-visible="subPath"]'),
  unlinkedCell: query<HTMLButtonElement>('[data-style-visible="unlinkedCell"]'),
  visit: query<HTMLButtonElement>('[data-style-visible="visit"]'),
  wall: query<HTMLButtonElement>('[data-style-visible="wall"]'),
}
